### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by Akshay0701** [Akshay0701/food_delivery_app#1]
i am able to run flutter app in chrome but when i tried to run it in my phone it shows me this :-

i also attached flutter doc in bottom 

Running Gradle task 'assembleDebug'...

Compiler message:
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/top_level.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/js-0.6.2/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/js-0.6.2/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
export 'dart:js_util';
^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:306:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:310:26: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var errorWrapper = allowInterop((e) => _changeController.addError(e));
                         ^^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:340:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:345:11: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          allowInterop((e) => _idTokenChangedController.addError(e));
          ^^^^^^^^^^^^
     
/E:/flutter/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:5: Error: Method not found: 'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatformMessage);
    ^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:29:7: Error: Method not found: 'hasProperty'.
  if (util.hasProperty(jsObject, 'firestore') &&
      ^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:30:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(jsObject, 'id') &&
      ^^^^^^^^^^^
dartlang.org/firebase-7.3.0/lib/src/utils.dart:53:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(proto, 'toBase64')) {
      ^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:67:24: Error: Method not found: 'getProperty'.
    map[key] = dartify(util.getProperty(jsObject, key));
                       ^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:91:17: Error: Method not found: 'newObject'.
    var jsMap = util.newObject();
                ^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:93:7: Error: Method not found: 'setProperty'.
      util.setProperty(jsMap, key, jsify(value));
      ^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:116:12: Error: Method not found: 'allowInterop'.
    return allowInterop(dartObject);
           ^^^^^^^^^^^^
/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:124:5: Error: Method not found: 'callMethod'.

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 64

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Picked up _JAVA_OPTIONS: -Xmx512M
Exception: Gradle task assembleDebug failed with exit code 1

# flutter doctor -v here 

E:\flutterproject\sample projects for study\flutter_web>flutter doctor -v
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.17134.1488], locale en-US)
    • Flutter version 1.17.0 at E:\flutter\flutter
    • Framework revision d3ed9ec945 (3 months ago), 2020-04-06 14:07:34 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ADMIN\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (3 available)
    • GM1911     • dab8456c   • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by Akshay0701** [comment]
> i am able to run flutter app in chrome but when i tried to run it in my phone it shows me this :-
> 
> i also attached flutter doc in bottom
> 
> Running Gradle task 'assembleDebug'...
> 
> Compiler message:
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/top_level.dart:1:8: Error: Not found: 'dart:html'
> import 'dart:html';
> ^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/js-0.6.2/lib/js.dart:8:1: Error: Not found: 'dart:js'
> export 'dart:js' show allowInterop, allowInteropCaptureThis;
> ^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/js-0.6.2/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
> export 'dart:js_util';
> ^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:306:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
> 
> * 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
>   var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
>   ^^^^^^^^^^^^
>   /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:310:26: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
> * 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
>   var errorWrapper = allowInterop((e) => _changeController.addError(e));
>   ^^^^^^^^^^^^
>   /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:340:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
> * 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
>   var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
>   ^^^^^^^^^^^^
>   /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:345:11: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
> * 'Auth' is from 'package:firebase/src/auth.dart' ('/C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
>   allowInterop((e) => _idTokenChangedController.addError(e));
>   ^^^^^^^^^^^^
> 
> /E:/flutter/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:5: Error: Method not found: 'webOnlySetPluginHandler'.
> ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatformMessage);
> ^^^^^^^^^^^^^^^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:29:7: Error: Method not found: 'hasProperty'.
> if (util.hasProperty(jsObject, 'firestore') &&
> ^^^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:30:7: Error: Method not found: 'hasProperty'.
> util.hasProperty(jsObject, 'id') &&
> ^^^^^^^^^^^
> dartlang.org/firebase-7.3.0/lib/src/utils.dart:53:7: Error: Method not found: 'hasProperty'.
> util.hasProperty(proto, 'toBase64')) {
> ^^^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:67:24: Error: Method not found: 'getProperty'.
> map[key] = dartify(util.getProperty(jsObject, key));
> ^^^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:91:17: Error: Method not found: 'newObject'.
> var jsMap = util.newObject();
> ^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:93:7: Error: Method not found: 'setProperty'.
> util.setProperty(jsMap, key, jsify(value));
> ^^^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:116:12: Error: Method not found: 'allowInterop'.
> return allowInterop(dartObject);
> ^^^^^^^^^^^^
> /C:/Users/ADMIN/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:124:5: Error: Method not found: 'callMethod'.
> 
> Run 'flutter -h' (or 'flutter -h') for available flutter commands and options.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'E:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'E:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 64
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 26s
> Picked up _JAVA_OPTIONS: -Xmx512M
> Exception: Gradle task assembleDebug failed with exit code 1
> 
> # flutter doctor -v here
> E:\flutterproject\sample projects for study\flutter_web>flutter doctor -v
> [√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.17134.1488], locale en-US)
> • Flutter version 1.17.0 at E:\flutter\flutter
> • Framework revision d3ed9ec945 (3 months ago), 2020-04-06 14:07:34 -0700
> • Engine revision ef9215ceb2
> • Dart version 2.9.0 (build 2.9.0-8.2.beta)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at C:\Users\ADMIN\AppData\Local\Android\sdk
> • Platform android-29, build-tools 29.0.2
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
> • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 47.1.2
> • Dart plugin version 193.7361
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.46.1)
> • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.12.1
> 
> [√] Connected device (3 available)
> • GM1911 • dab8456c • android-arm64 • Android 10 (API 29)
> • Chrome • chrome • web-javascript • Google Chrome 83.0.4103.116
> • Web Server • web-server • web-javascript • Flutter Tools
> 
> • No issues found!

**Comment by shzadrasool** [comment]
am facing same issue..any solution?
