### ISSUE TITLE
Is there any guidelines how to develop ?any youtube tutorial or other source?

### ISSUE THREAD

**Issue by hawk7476** [Akshay0701/food_delivery_app#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Akshay0701** [comment]
Sorry I can't understand you problem, 

how YouTube/tutorial is related to this project?

**Comment by hawk7476** [comment]
yes Actually I am new.So I want to learn how to make food app like you have
developed

**Comment by Akshay0701** [comment]
Okay, then I would recommend [this](https://www.youtube.com/watch?v=WBe1orPAKuM) video for learning food app development with flutter
