### ISSUE TITLE
Setup Instruction

### ISSUE THREAD

**Issue by hitman3r44** [Akshay0701/food_delivery_app#12]
Hi,

Is there any document to set up this project in the local ith firebase dataset. Anyway, can we export the dataset from firebase. 
Thanks in advance.

**Comment by Akshay0701** [comment]
Hello @hitman3r44, 
there is no wiki page I created for set up this project in local machine,
for that just fork the project, get pull the branch to local using get commands, and then you can run this project like flutter project.

yes surely we can export the dataset from firebase, but I didn't give access to the firebase of this flutter project to anyone

Thank you

**Comment by hitman3r44** [comment]
@Akshay0701  thanks for your reply, I just wanted a backup copy of the dataset, not wanting the firebase access, I will import the dataset into my firebase, if its possible will be helpful for me, thanks again
