### ISSUE TITLE
[Bug] User is not able to scroll the page till bottom

### ISSUE THREAD

**Issue by Akshay0701** [Akshay0701/food_delivery_app#14]
###### Reproduction Steps

1. open home
2. open myorder
3. try to scroll the page

### Recording 
![20211001_182056](https://user-images.githubusercontent.com/52353967/135622652-8d5e44e2-87f7-4f26-93a0-cfad0ec3c80f.gif)

###### Expected Result
user should be able to scroll through the page

###### Actual Result
user is not able to scroll the page till bottom

###### Debug info
Refer to the [support page](https://github.com/Akshay0701/food_delivery_app) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I am reporting a bug or enhancement request specific to food_delivery_app
- [ ] I have checked the https://github.com/Akshay0701/food_delivery_app and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://github.com/Akshay0701/food_delivery_app))

**Comment by PranshuPandya** [comment]
I am very well familiar with dart and flutter. please assign this to me i will do it.

**Comment by Akshay0701** [comment]
cool

**Comment by Akshay0701** [comment]
close with #17
