### ISSUE TITLE
[Bug] button size gets large in landscape mode 

### ISSUE THREAD

**Issue by Akshay0701** [Akshay0701/food_delivery_app#15]
###### Reproduction Steps

1. open home
2. open food detail page
3. turn phone to landscape mode

### Landscape Screenshot
![b3a539fb-7c38-41a6-8b40-17dc70541bc0](https://user-images.githubusercontent.com/52353967/135623783-7b76ea32-408d-4b33-ae45-27c05ce9a687.jpg)

### Portrait Screenshot
![20e98e4e-711d-4545-af14-0913fa4b146d](https://user-images.githubusercontent.com/52353967/135624062-45990da1-3c81-450c-95b2-a272fa0e2065.jpg)

###### Expected Result
size of button in portrait and landscape should be same 

###### Actual Result
height gets large in landscape mode as compare to portrait mode

###### Debug info
Refer to the [support page](https://github.com/Akshay0701/food_delivery_app) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I am reporting a bug or enhancement request specific to food_delivery_app
- [ ] I have checked the https://github.com/Akshay0701/food_delivery_app and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://github.com/Akshay0701/food_delivery_app))

**Comment by SAKSHAM-SUDO** [comment]
I can do that

**Comment by SAKSHAM-SUDO** [comment]
Means i will try it

**Comment by Akshay0701** [comment]
yes, give it a shot..

**Comment by SAKSHAM-SUDO** [comment]
Should I fix the height of the button?

**Comment by Akshay0701** [comment]
yes

**Comment by SAKSHAM-SUDO** [comment]
ok

**Comment by Akshay0701** [comment]
closed with #21
