### ISSUE TITLE
Added Google Json File and removed some errors

### ISSUE THREAD

**Issue by SAKSHAM-SUDO** [Akshay0701/food_delivery_app#16]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://github.com/Akshay0701/food_delivery_app) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I am reporting a bug or enhancement request specific to food_delivery_app
- [x] I have checked the https://github.com/Akshay0701/food_delivery_app and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://github.com/Akshay0701/food_delivery_app))

**Comment by Akshay0701** [comment]
i dont prefer to add google json key file directly to github repo where every one can get access to my server with that key file, that is the reason I removed json file.
