### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vpshare1234** [Akshay0701/food_delivery_app#22]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://github.com/Akshay0701/food_delivery_app) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I am reporting a bug or enhancement request specific to food_delivery_app
- [ ] I have checked the https://github.com/Akshay0701/food_delivery_app and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://github.com/Akshay0701/food_delivery_app))

**Comment by Akshay0701** [comment]
is there any specific bug you noticed ?
if not, then please don't spam issues
