### ISSUE TITLE
A firebase database demo

### ISSUE THREAD

**Issue by MahmoudiOussama** [Akshay0701/food_delivery_app#26]
I wanted to test this project, by running it, I created my own firebase project, enabled auth, realtime database and firestore.
But the most important is what type of data should I fill my database with ?
Isn't there any data demo to import and try running this project with?

**Comment by Safras15** [comment]
@Akshay0701

**Comment by Akshay0701** [comment]
give me your mail id's i will send you personally..

**Comment by Safras15** [comment]
send it to this email

**Comment by Safras15** [comment]
@Akshay0701 safrasfaizer15@gmail.com

**Comment by Safras15** [comment]
@Akshay0701

**Comment by Safras15** [comment]
@Akshay0701
