### ISSUE TITLE
Improve UI Design Of Login Screen

### ISSUE THREAD

**Issue by Akshay0701** [Akshay0701/food_delivery_app#3]
if you have good ui designing skill , please improve login ui design ,Thanks /

**Comment by faz1993** [comment]
@Akshay0701 is it only design ui or its an app functionable ?

**Comment by Akshay0701** [comment]
It's fully functional app ,but I just want to change the design of login page for now .

**Comment by Akshay0701** [comment]
If you want to change , then I will assign this to you .

**Comment by faz1993** [comment]
@Akshay0701 i can help ya

**Comment by Akshay0701** [comment]
yeah ,i know why that happen , its taking random value from 3.5-5.0 , and when ever you press + app state change and hole UI Change its state ,thats why again it randomly select value from  3.5-5.0 .

**Comment by Akshay0701** [comment]
could you able to implement any state management technic ?

**Comment by badushaebrahim** [comment]
hi can i help

**Comment by Akshay0701** [comment]
Sure

**Comment by Akshay0701** [comment]
@badushaebrahim are you still working on this issue?

or should I take solve it?

**Comment by Akshay0701** [comment]
@badushaebrahim are you still working on this issue?

or should I solve it?

**Comment by SAKSHAM-SUDO** [comment]
Can I change work on this issue

**Comment by SAKSHAM-SUDO** [comment]
Can I work on this issue

**Comment by Akshay0701** [comment]
Sure go on

**Comment by SAKSHAM-SUDO** [comment]
Can you tell me what changes have to be done?
\

**Comment by Akshay0701** [comment]
Current UI is like this, could you make better UI for Login page(you can pitch your own ideas to in this)
![Screenshot_20211001-161448.jpg](https://user-images.githubusercontent.com/52353967/135607477-c48a6ed6-0df8-49bb-93a9-12d19a420c80.jpg)

**Comment by SAKSHAM-SUDO** [comment]
Ok

**Comment by karanpatel2329** [comment]
Hello Ashay,
i can help you to improve app design. Please assigned this issue to me.
Thank You.

**Comment by SAKSHAM-SUDO** [comment]
Hey Ashay thanks for you kind gesture. But i can do it alone

**Comment by Akshay0701** [comment]
> Hello Ashay, i can help you to improve app design. Please assigned this issue to me. Thank You.

thanks for your interest, but Saksham is assigned currently,
till then, can you please find out few bugs from this application?

**Comment by SAKSHAM-SUDO** [comment]
Bro there are some errors in your project

**Comment by Akshay0701** [comment]
create issue for that

**Comment by SAKSHAM-SUDO** [comment]
![Capture](https://user-images.githubusercontent.com/54800729/135657808-6fd7752f-1ced-4b95-92fd-30046c4b24fd.PNG)

**Comment by SAKSHAM-SUDO** [comment]
Google Json file also missing

**Comment by SAKSHAM-SUDO** [comment]
Please provide me

**Comment by Akshay0701** [comment]
json file:
https://github.com/Akshay0701/food_delivery_app/blob/242da8793b5e55d766ee25cd3b9a3d733417f6a8/android/app/google-services.json

**Comment by SAKSHAM-SUDO** [comment]
![WhatsApp Image 2021-10-01 at 11 17 26 PM](https://user-images.githubusercontent.com/54800729/135664863-80aa3c14-83a7-4280-98f3-0a2cb8709b11.jpeg)
is that okay

**Comment by Akshay0701** [comment]
nice Thanks, can you use the food logo?

**Comment by SAKSHAM-SUDO** [comment]
Ok
