### ISSUE TITLE
From where the admin will receive the order or The Delivery Person

### ISSUE THREAD

**Issue by Karandhot** [Akshay0701/food_delivery_app#7]
Please tell us how we will receive the order and Deliver it.

**Comment by Akshay0701** [comment]
this project is incomplete , i am really sorry about that , order do get store in firebase database but there is no admin panel

**Comment by Karandhot** [comment]
> this project is incomplete , i am really sorry about that , order do get store in firebase database but there is no admin panel 

Thank you very much the information was priceless.
